version: '3'

services:
  api:
    build:
      context: ./apps/api
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data: